---
- name: Remove conflicting Elasticsearch repository
  ansible.builtin.apt_repository:
    repo: "{{ elasticsearch_repo }}"
    state: absent

- name: Import the Elasticsearch GPG key
  apt_key:
    url: "{{ elasticsearch_gpg_key_url }}"
    state: present

- name: Adding Elasticsearch APT repository
  apt_repository:
    repo: "{{ elasticsearch_repo }}"
    state: present
    filename: "{{ elasticsearch_repo_filename }}"
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: "{{ elasticsearch_package_name }}"
    state: present
    update_cache: yes

- name: Reload systemd config
  systemd:
    daemon_reload: yes

- name: Enable Elasticsearch service and ensure it is not masked
  systemd:
    name: "{{ elasticsearch_service_name }}"
    enabled: yes
    masked: no

- name: Update Elasticsearch configuration
  template:
    src: "{{ elasticsearch_config_template_src }}"
    dest: "{{ elasticsearch_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch is running
  systemd:
    state: started
    name: "{{ elasticsearch_service_name }}"

- name: Verify Elasticsearch is running
  command: curl -X GET "localhost:9200/"
  register: result

- debug:
    var: result.stdout
