---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx for Magento
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/magento2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
