---
- name: Install PHP and necessary extensions
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes

- name: Update php.ini file
  template:
    src: "{{ php_ini_template_src }}"
    dest: "{{ php_ini_dest }}"
    owner: "{{ php_ini_owner }}"
    group: "{{ php_ini_group }}"
    mode: "{{ php_ini_mode }}"
  notify: Restart Nginx

