---
- name: Ensure MySQL is installed
  apt:
    name: mysql-server
    state: present

- name: APT update
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure MySQL Python libraries are installed.
  ansible.builtin.apt:
    name: "{{ mysql_python_package_debian }}"
    state: present

# - name: Make sure pymysql is present
#   become: true # needed if the other tasks are not played as root
#   pip:
#     name: pymysql
#     state: present

- name: Ensure MySQL is listening on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mysql

- name: Create datadir if it does not exist
  ansible.builtin.file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
    setype: mysqld_db_t

- name: Ensure MySQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ mysql_daemon }}"
    state: started
    enabled: "{{ mysql_enabled_on_startup }}"
  register: mysql_service_configuration



